user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.EditProfile.as_view(), name='editprofile'),
    path('', views.EditProfile.as_view(), name='user')
]

yaas/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import auction.services
import auction.views
import user.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auction/', include('auction.urls', namespace='auction')),
    path('user/', include('user.urls', namespace='user')),
    path('', auction.views.Index.as_view(), name='index'),
    path('signup/', user.views.SignUp.as_view(), name='signup'),
    path('signin/', user.views.SignIn.as_view(), name='signin'),
    path('signout/', user.views.signout, name='signout'),
    path('changeLanguage/<lang_code>/', auction.views.changeLanguage, name='changeLanguage'),
    path('changeCurrency/<currency_code>/', auction.views.changeCurrency, name='changeCurrency')
]

urlpatterns += [
    path('api/v1/browse/', auction.services.BrowseAuctionApi.as_view(), name='browseauctionsapi'),
    re_path(r'^api/v1/search/(\w+)/?$', auction.services.SearchAuctionApi.as_view(), name='searchauctionapi'),
    re_path(r'^api/v1/search/\??(?:&?[^=&]*=[^=&]*)*', auction.services.SearchAuctionWithTermApi.as_view(),
            name='searchauctionwithtermapi'),
    re_path(r'^api/v1/searchid/(\d+)/$', auction.services.SearchAuctionApiById.as_view(), name='searchauctionbyidapi'),
    re_path(r'^api/v1/bid/(\d+)/$', auction.services.BidAuctionApi.as_view(), name='bidauctionapi'),

    path('generatedata', auction.services.GenerateDataAPI.as_view(), name="generatedataapi")
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Language(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    language = models.CharField(max_length=8, default='en')


@receiver(post_save, sender=User)
def create_user_language(sender, instance, created, **kwargs):
    if created:
        Language.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_language(sender, instance, **kwargs):
    instance.language.save()

user/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import translation
from django.utils.decorators import method_decorator
from django.views import View

from user.utils import *
from yaas.settings import LANGUAGE_COOKIE_NAME


class SignUp(View):
    def get(self, request):
        return render(request, 'signupform.html', {
            'form': CreateSignupForm(),
            'email_taken': False,
            'username_taken': False
        }, status=200)

    def post(self, request):
        form = CreateSignupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            try:
                User.objects.get(username=cd['username'])
                return render(request, 'signupform.html', {
                    'form': CreateSignupForm(),
                    'email_taken': False,
                    'username_taken': True
                }, status=200)
            except User.DoesNotExist:
                try:
                    User.objects.get(email=cd['email'])
                    return render(request, 'signupform.html', {
                        'form': CreateSignupForm(),
                        'email_taken': True,
                        'username_taken': False
                    }, status=200)
                except User.DoesNotExist:
                    user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
                    user.save()

                    return HttpResponseRedirect(reverse('index'), status=302)
        else:
            return render(request, 'signupform.html', {
                'form': CreateSignupForm(),
                'email_taken': False,
                'username_taken': False
            }, status=200)


class SignIn(View):
    def get(self, request):
        return render(request, 'sigininform.html', {
            'form': CreateSigninForm(),
            'wrong': False
        }, status=200)

    def post(self, request):
        form = CreateSigninForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                translation.activate(user.language.language)
                response = HttpResponseRedirect(reverse('index'), status=302)
                response.set_cookie(LANGUAGE_COOKIE_NAME, user.language.language)
                return response
            else:
                return render(request, 'sigininform.html', {
                    'form': CreateSigninForm(),
                    'wrong': True
                }, status=401)
        else:
            return render(request, 'sigininform.html', {
                'form': CreateSigninForm(),
                'wrong': False
            }, status=401)


def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'), status=302)


@method_decorator(login_required, name='dispatch')
class EditProfile(View):
    def get(self, request):
        return render(request, 'profile.html', {'form': CreateEditAccountForm()}, status=200)

    def post(self, request):
        form = CreateEditAccountForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            if cd['email']:
                try:
                    User.objects.get(email=cd['email'])
                    return render(request, 'profile.html', {'form': CreateEditAccountForm()}, status=200)
                except User.DoesNotExist:
                    user = User.objects.get(username=request.user)
                    user.email = cd['email']
                    user.save()

            if cd['password']:
                user = User.objects.get(username=request.user)
                user.set_password(cd['password'])
                user.save()
                update_session_auth_hash(request, user)

            return HttpResponseRedirect(reverse('user:user'), status=302)

        return render(request, 'profile.html', {'form': CreateEditAccountForm()}, status=200)

user/templates/profile.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>User profile</title>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            document.querySelector('#editMode').setAttribute("style", "display:none");

            document.querySelector('#edit').addEventListener("click", () => {
                document.querySelector('#default').setAttribute("style", "display:none");
                document.querySelector('#editMode').setAttribute("style", "display:block");
            })
        });
    </script>
</head>
<body>
    <h1>My profile</h1>
    <form id="editMode" action="{% url 'user:editprofile' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <div id="default">
        <p>Username: {{ user.username }}</p>
        <p>Email: {{ user.email }}</p>
        <button type="button" id="edit">Edit profile</button>
    </div>
</body>
</html>

user/templates/sigininform.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Login to YaaS
{% endblock %}

{% block content %}
    <h1>Login</h1>
    <form action="{% url 'signin' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if wrong %}
            <p>Wrong username or password.</p>
        {% endif %}
        <input type="submit" value="Submit">
    </form>
    <p>No account? <a href="{% url 'signup' %}">Register</a></p>
{% endblock %}

user/templates/signupform.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Signup to YaaS
{% endblock %}

{% block content %}
    <h1>Signup</h1>
    <form action="{% url 'signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if email_taken %}
            <p>This email has been taken.</p>
        {% endif %}
        {% if username_taken %}
            <p>This username has been taken.</p>
        {% endif %}
        <input type="submit" value="Submit">
    </form>
    <p>Already have an account? <a href="{% url 'signin' %}">Login</a></p>
{% endblock %}