auction/urls.py
from django.urls import path, re_path
from . import views


app_name = 'auction'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.CreateAuction.as_view(), name='create'),
    re_path(r'(create|edit|bid|ban)/success/', views.success, name='success'),
    path('create/error', views.edit_auction_error, name='forbidden'),
    re_path(r'^edit/(\d+)/$', views.EditAuction.as_view(), name='edit'),
    re_path(r'^edit/(\S+)/$', views.EditSigned.as_view(), name='edit_signed'),
    re_path(r'^bid/(\d+)/$', views.bid, name='bid'),
    re_path(r'^ban/(\d+)$', views.ban, name='ban'),
    path('resolve/', views.resolve, name='resolve')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.EditProfile.as_view(), name='editprofile'),
    path('', views.EditProfile.as_view(), name='user')
]

yaas/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import auction.services
import auction.views
import user.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auction/', include('auction.urls', namespace='auction')),
    path('user/', include('user.urls', namespace='user')),
    path('', auction.views.Index.as_view(), name='index'),
    path('signup/', user.views.SignUp.as_view(), name='signup'),
    path('signin/', user.views.SignIn.as_view(), name='signin'),
    path('signout/', user.views.signout, name='signout'),
    path('changeLanguage/<lang_code>/', auction.views.changeLanguage, name='changeLanguage'),
    path('changeCurrency/<currency_code>/', auction.views.changeCurrency, name='changeCurrency')
]

urlpatterns += [
    path('api/v1/browse/', auction.services.BrowseAuctionApi.as_view(), name='browseauctionsapi'),
    re_path(r'^api/v1/search/(\w+)/?$', auction.services.SearchAuctionApi.as_view(), name='searchauctionapi'),
    re_path(r'^api/v1/search/\??(?:&?[^=&]*=[^=&]*)*', auction.services.SearchAuctionWithTermApi.as_view(),
            name='searchauctionwithtermapi'),
    re_path(r'^api/v1/searchid/(\d+)/$', auction.services.SearchAuctionApiById.as_view(), name='searchauctionbyidapi'),
    re_path(r'^api/v1/bid/(\d+)/$', auction.services.BidAuctionApi.as_view(), name='bidauctionapi'),

    path('generatedata', auction.services.GenerateDataAPI.as_view(), name="generatedataapi")
]

auction/models.py
from django.db import models


class AuctionModel(models.Model):
    ACTIVE = 'AC'
    BANNED = 'BN'
    DUE = 'DU'
    ADJUDECATED = 'AD'
    STATUSES = [
        (ACTIVE, 'Active'),
        (BANNED, 'Banned'),
        (DUE, 'Due'),
        (ADJUDECATED, 'Adjudecated')
    ]
    seller = models.IntegerField()
    title = models.CharField(max_length=256)
    description = models.TextField(max_length=3000)
    minimum_price = models.FloatField()
    deadline_date = models.DateTimeField()
    status = models.CharField(max_length=12, choices=STATUSES, default=ACTIVE)
    highest_bid = models.FloatField(default=0)
    highest_bidder = models.IntegerField(default=-1)
    bidders = models.TextField(default="[]")
    version = models.IntegerField(default=0)

auction/views.py
import json
from datetime import datetime, timedelta, timezone

import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import signing
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.timezone import make_aware
from django.views import View
from django.views.decorators.http import require_POST, require_GET

from auction.models import AuctionModel
from auction.utils import CreateAuctionForm, EditAuctionForm, set_currencies, generate_response
from yaas.settings import LANGUAGE_COOKIE_NAME, CURRENCY_API, CURRENCY_COOKIE_NAME


class Index(View):
    def get(self, request):
        auctions = AuctionModel.objects.filter(status=AuctionModel.ACTIVE)
        currency = set_currencies(request, auctions)

        return render(request, 'index.html', {'auctions': auctions, 'currency': currency}, status=200)


def search(request):
    if request.GET['term'].lower() != '':
        criteria = request.GET['term'].lower().strip()
        if request.user.is_superuser:
            auctions = AuctionModel.objects.filter(title__contains=criteria)
        else:
            auctions = AuctionModel.objects.filter(title__contains=criteria, status=AuctionModel.ACTIVE)
    else:
        if request.user.is_superuser:
            auctions = AuctionModel.objects.all()
        else:
            auctions = AuctionModel.objects.filter(status=AuctionModel.ACTIVE)

    currency = set_currencies(request, auctions)
    return render(request, "index.html", {'auctions': auctions, 'search': True, 'currency': currency}, status=200)


@method_decorator(login_required, name='dispatch')
class CreateAuction(View):
    def get(self, request):
        return render(request, 'createAuction.html', {'form': CreateAuctionForm()}, status=200)

    def post(self, request):
        form = CreateAuctionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            deadline_date = cd['deadline_date']
            minimum_price = cd['minimum_price']

            try:
                deadline_date = datetime.strptime(deadline_date, '%d.%m.%Y %H:%M:%S')
            except ValueError:
                return render(request, 'createAuction.html', {'form': form, 'err': 'format'}, status=200)

            if (datetime.now() + timedelta(hours=72)) > deadline_date:
                return render(request, 'createAuction.html', {'form': form, 'err': 'deadline'}, status=200)

            if minimum_price < 0.01:
                return render(request, 'createAuction.html', {'form': form, 'err': 'min'}, status=200)

            user = User.objects.get(username=request.user)
            auction = AuctionModel(seller=user.id, title=cd['title'], description=cd['description'],
                                   minimum_price=minimum_price, deadline_date=make_aware(deadline_date),
                                   highest_bid=minimum_price)
            auction.save()

            signed_url = request.get_host() + reverse('auction:edit_signed', args=(signing.dumps({
                "username": user.username,
                "auction": auction.id
            }),))

            msg = EmailMessage(
                'Auction has been created successfully',
                'Auction has been created successfully. This is the link to your <a href="' +
                signed_url + '">auction</a>',
                'yaas-no-reply@yaas.com',
                [User.objects.get(username=request.user).email]
            )
            msg.content_subtype = "html"
            msg.send()

            return HttpResponseRedirect(reverse('auction:success', args=("create",)), status=302)
        else:
            return render(request, 'createAuction.html', {'form': CreateAuctionForm()}, status=200)


def success(request, param):
    if param == "edit":
        return generate_response("Auction has been updated successfully")
    elif param == "create":
        return generate_response("Auction has been created successfully")
    elif param == "bid":
        return generate_response("You has bid successfully")
    elif param == "ban":
        return generate_response("Ban successfully")


@method_decorator(login_required, name='dispatch')
class EditAuction(View):
    def get(self, request, auction_id):
        user = User.objects.get(username=request.user)
        auction = AuctionModel.objects.get(id=auction_id)

        if auction.seller is not user.id:
            return HttpResponseRedirect(reverse('auction:forbidden'), status=302)
        else:
            return render(request, 'editAuction.html', {'form': EditAuctionForm(initial={
                'title': auction.title,
                'description': auction.description
            }), 'id': auction.id}, status=200)

    def post(self, request, auction_id):
        user = User.objects.get(username=request.user)
        auction = AuctionModel.objects.get(id=auction_id)

        if auction.seller is not user.id:
            return HttpResponseRedirect(reverse('auction:forbidden'), status=302)
        else:
            form = EditAuctionForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                auction.description = cd['description']
                auction.version = auction.version + 1
                auction.save()

                return HttpResponseRedirect(reverse('auction:success', args=("edit",)), status=302)
            else:
                return render(request, 'editAuction.html', {'form': EditAuctionForm(initial={
                    'title': auction.title,
                    'description': auction.description
                }), 'id': auction.id}, status=200)


class EditSigned(View):
    def get(self, request, signature):
        try:
            signed_object = signing.loads(signature)
        except signing.BadSignature:
            return generate_response("You tried to edit a non-existing auction.")

        auction = AuctionModel.objects.get(id=signed_object['auction'])

        return render(request, 'editAuction.html', {'form': EditAuctionForm(initial={
            'title': auction.title,
            'description': auction.description
        }), 'secret': signature}, status=200)

    def post(self, request, signature):
        try:
            signed_object = signing.loads(signature)
        except signing.BadSignature:
            return generate_response("You tried to edit a non-existing auction.")

        auction = AuctionModel.objects.get(id=signed_object['auction'])
        form = EditAuctionForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            auction.description = cd['description']
            auction.version = auction.version + 1
            auction.save()

            return HttpResponseRedirect(reverse('auction:success', args=("edit",)), status=302)
        else:
            return render(request, 'editAuction.html', {'form': EditAuctionForm(initial={
                'title': auction.title,
                'description': auction.description
            }), 'secret': signature}, status=200)


def edit_auction_error(request):
    return generate_response("That is not your auction to edit.")


@login_required()
def bid(request, auction_id):
    user = User.objects.get(username=request.user)
    auction = AuctionModel.objects.get(id=auction_id)
    amount = float("{0:.2f}".format(float(request.POST['new_price'])))

    if "version" in request.POST:
        if int(request.POST["version"]) != auction.version:
            return render(request, 'bidVersioning.html', {'auction': auction}, status=200)

    if auction.seller is user.id:
        return generate_response("You cannot bid on your own auctions")

    if auction.status != AuctionModel.ACTIVE:
        return generate_response("You can only bid on active auctions")

    if auction.deadline_date < datetime.now(timezone.utc):
        return generate_response("You can only bid on active auctions")

    if int(amount * 100) < int(auction.highest_bid * 100) + 1:
        return generate_response("New bid must be greater than the current bid for at least 0.01")

    auction.highest_bid = amount
    auction.highest_bidder = user.id
    bidders = json.loads(auction.bidders)
    bidders.append(user.id)
    auction.bidders = json.dumps(bidders)
    auction.version = auction.version + 1
    auction.save()

    send_mail(
        'Auction has been bid',
        'Auction #' + str(auction.id) + ' has a new highest bid',
        'yaas-no-reply@yaas.com',
        [User.objects.get(id=auction.seller).email],
        fail_silently=False,
    )

    send_mail(
        'You have bid an auction',
        'You have the highest bid to auction #' + str(auction.id),
        'yaas-no-reply@yaas.com',
        [User.objects.get(id=user.id).email],
        fail_silently=False,
    )

    return HttpResponseRedirect(reverse('auction:success', args=("bid",)), status=302)


@require_POST
@login_required()
def ban(request, auction_id):
    user = User.objects.get(username=request.user)
    auction = AuctionModel.objects.get(id=auction_id)

    if not user.is_superuser:
        return HttpResponseRedirect(reverse('index'), status=302)

    auction.status = AuctionModel.BANNED
    bidders = json.loads(auction.bidders)
    bidders.append(auction.seller)
    for user_id in bidders:
        send_mail(
            'Auction banned',
            'Auction #' + str(auction.id) + ' has been banned',
            'yaas-no-reply@yaas.com',
            [User.objects.get(id=user_id).email],
            fail_silently=False,
        )
    auction.save()

    return HttpResponseRedirect(reverse('auction:success', args=("ban",)), status=302)


def resolve(request):

auction/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container pt-2 pb-5 mb-5">
    <ul class="nav nav-pills nav-fill mt-3 mb-5">
        {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'signin' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
        {% else %}
            <li class="nav-item">
                <span class="nav-link active">Username: {{ user.username }}</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:user' %}">User profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auction:create' %}">Create Auction</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signout' %}">Logout</a>
            </li>
        {% endif %}
        <li class="nav-item text-secondary ml-5" style="line-height: 2.4em">
            {% trans "Change language to" %}
        </li>
        <li class="nav-item">
            {% ifequal LANGUAGE_CODE "en" %}
                <a class="nav-link active bg-secondary" href="{% url 'changeLanguage' lang_code='sv' %}">{% trans "Swedish" %}</a>
            {% else %}
                <a class="nav-link active bg-secondary" href="{% url 'changeLanguage' lang_code='en' %}">{% trans "English" %}</a>
            {% endifequal %}
        </li>
        <li class="nav-item text-secondary ml-5" style="line-height: 2.4em">
            {% trans "Change currency to" %}
        </li>
        <li class="nav-item">
            {% ifequal currency "usd" %}
                <a class="nav-link active bg-secondary" href="{% url 'changeCurrency' currency_code='eur' %}">EUR</a>
            {% else %}
                <a class="nav-link active bg-secondary" href="{% url 'changeCurrency' currency_code='usd' %}">USD</a>
            {% endifequal %}
        </li>
    </ul>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

auction/templates/bidVersioning.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Auction {{ auction.title }} has changed
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h1>"{{ auction.title }}" has changed</h1>
            <p>While you were bidding, the auction description or latest bid was updated. These are its latest
                details.</p>
            <p>You can still bid if you want to.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-lg-4">
            <div class="card my-3 shadow bd-callout">
                <div class="card-body">
                    <h4 class="card-title">{{ auction.title }}</h4>
                    <p class="card-text">{{ auction.description|default_if_none:"no description" }}</p>
                    <p>Auction version {{ auction.version }}</p>
                    {% ifequal currency "usd" %}
                        <p class="card-text">{% trans "Minimum price:" %}
                            ${{ auction.minimum_price|stringformat:".2f" }}</p>
                        <p class="card-text">{% trans "Highest bid:" %}
                            ${{ auction.highest_bid|stringformat:".2f" }}</p>
                    {% else %}
                        <p class="card-text">{% trans "Minimum price:" %} {{ auction.minimum_price|stringformat:".2f" }}€</p>
                        <p class="card-text">{% trans "Highest bid:" %} {{ auction.highest_bid|stringformat:".2f" }}€</p>
                    {% endifequal %}
                    <p class="card-text">{% trans "Deadline:" %} {{ auction.deadline_date }}</p>
                </div>
                {% if user.is_authenticated %}
                    <div class="card-footer text-muted">
                        <form class="input-group" action="{% url 'auction:bid' auction.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="version" value="{{ auction.version }}" />
                            <input type="number" name="new_price" step="0.01" class="form-control"
                                   placeholder="{{ auction.highest_bid|stringformat:".2f" }}€" aria-label="New bid"/>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-outline-success">Bid in auction</button>
                            </div>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

auction/templates/createAuction.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Create Auction
{% endblock %}

{% block content %}
    <script type="text/javascript">
        let form = document.getElementById('form');

        function clicked() {
           if (confirm('Do you want to submit?')) {
               form.submit();
           } else {
               return false;
           }
        }
    </script>
    <h1>Create a new auction</h1>
    <form id="form" action="{% url 'auction:create' %}" method="post">
        {% csrf_token %}
        {% if err == 'deadline' %}
            <p>The deadline date should be at least 72 hours from now</p>
        {% elif err == 'format' %}
            <p>Enter a valid date/time. Format is '%d.%m.%Y %H:%M:%S'</p>
        {% elif err == 'min' %}
            <p>Ensure this value is greater than or equal to 0.01</p>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" onclick="clicked()" value="Submit">
    </form>
{% endblock %}

auction/templates/editAuction.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Edit auction {{ id }}
{% endblock %}

{% block content %}
    <h1>Edit Auction #{{ id }}</h1>
    {% if secret %}
        <form action="{% url 'auction:edit_signed' secret %}" method="post">
    {% else %}
        <form action="{% url 'auction:edit' id %}" method="post">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

auction/templates/generateData.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Generate Data
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Generate data automatically</h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <p>We have generated the following {{ users|length }} users.</p>
            <table class="table table-striped table-hover">
                <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">username</th>
                    <th scope="col">email</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <th scope="row">{{ user.id }}</th>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <p>We have generated the following {{ auctions|length }} auctions.</p>
            <table class="table table-striped">
                <thead class="thead-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Seller</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Minimum price</th>
                    <th scope="col">Bid</th>
                    <th scope="col">Deadline date</th>
                </tr>
                </thead>
                <tbody>
                {% for auction in auctions %}
                    <tr>
                        <th scope="row">{{ auction.id }}</th>
                        <td>{{ auction.seller }}</td>
                        <td>{{ auction.title }}</td>
                        <td>{{ auction.description|slice:":35" }}</td>
                        <td>{{ auction.minimum_price }}</td>
                        <td>{{ auction.highest_bid }}</td>
                        <td>{{ auction.deadline_date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <p>And some of the auctions have bids.</p>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <p>You can go back <a class="btn btn-sm btn-outline-primary" href="{% url 'index' %}">home</a></p>
        </div>
    </div>
{% endblock %}

auction/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    YaaS homepage
{% endblock %}

{% block content %}
    <div class="col-md-4">
        <h1>{% trans "Homepage" %}</h1>
    </div>
    <hr>
    <div class="col-lg-4">
        <h2>{% trans "Search auctions" %}</h2>
        <form class="input-group mb-3" action="{% url 'auction:search' %}" method="get">
            <input type="text" name="term" class="form-control" placeholder="Auction title terms"
                   aria-label="Auction title terms">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">{% trans "Search" %}</button>
            </div>
        </form>
        {% if search %}
            <h2>{% trans "Search result auctions:" %}</h2>
        {% else %}
            <h2>{% trans "Auctions" %}</h2>
        {% endif %}
    </div>

    <div class="row">
        {% for auction in auctions %}
            <div class="col-md-6 col-lg-4">
                <div class="card my-3 shadow bd-callout">
                    <div class="card-body">
                        <h4 class="card-title">{{ auction.title }}</h4>
                        <p class="card-text">{{ auction.description|default_if_none:"no description" }}</p>
                        <p>Auction version {{ auction.version }}</p>
                        {% ifequal currency "usd" %}
                            <p class="card-text">{% trans "Minimum price:" %}
                                ${{ auction.minimum_price|stringformat:".2f" }}</p>
                            <p class="card-text">{% trans "Highest bid:" %}
                                ${{ auction.highest_bid|stringformat:".2f" }}</p>
                        {% else %}
                            <p class="card-text">{% trans "Minimum price:" %} {{ auction.minimum_price|stringformat:".2f" }}€</p>
                            <p class="card-text">{% trans "Highest bid:" %} {{ auction.highest_bid|stringformat:".2f" }}€</p>
                        {% endifequal %}
                        <p class="card-text">{% trans "Deadline:" %} {{ auction.deadline_date }}</p>
                        {% if user.is_authenticated %}
                            <div class="mt-4">
                                <a class="btn btn-light"
                                   href="{% url 'auction:edit' auction.id %}">{% trans "Edit auction" %}</a>
                                {% if user.is_superuser %}
                                    {% if auction.status == 'BN' %}
                                        <p>{% trans "Auction is banned" %}</p>
                                    {% else %}
                                        <form class="d-inline float-right" action="{% url 'auction:ban' auction.id %}"
                                              method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-danger" type="submit">Ban auction</button>
                                        </form>
                                    {% endif %}
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                        {% if user.is_authenticated %}
                            <div class="card-footer text-muted">
                                <form class="input-group" action="{% url 'auction:bid' auction.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="version" value="{{ auction.version }}" />
                                    <input type="number" name="new_price" step="0.01" class="form-control"
                                           placeholder="{{ auction.highest_bid|stringformat:".2f" }}€" aria-label="New bid"/>
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-outline-success">Bid in auction</button>
                                    </div>
                                </form>
                            </div>
                        {% endif %}
                </div>
            </div>
        {% empty %}
            {% if user.is_authenticated %}
                <div class="col-md-4">
                    <p>You can be the first to <a href="{% url 'auction:create' %}"> create an auction</a>.</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="row pt-5">
        <div class="col-md-4">
            <h2>{% trans "Generate data" %}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>{% trans "You can generate data automatically by clicking" %}
                <a class="btn btn-sm btn-primary" href="{% url 'generatedataapi' %}">{% trans "here" %}</a>
            </p>
        </div>
    </div>
{% endblock %}